title: Ciao!
logo: /assets/img/sopressa-polenta.jpeg
description: CAD (Codificare, Analizzare, Diffondere) è una scuola dottorale di digital humanities finanziata dall'Associazione Internazionale Professori di Italiano (AIPI) e dall'Associazione per l'Informatica Umanistica e la Cultura Digitale (AIUCD).
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
