#title: CAD 2019
logo: /assets/img/CAD-blu.png
description: CAD (Codificare, Analizzare, Diffondere) è una scuola dottorale di informatica umanistica (digital humanities) finanziata dall'Associazione Internazionale Professori di Italiano.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
